# Generated by Django 5.2.1 on 2025-06-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_venta_fecha"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="stock_minimo",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
