# Generated by Django 5.2.1 on 2025-06-13 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_producto_stock_minimo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venta",
            name="cantidad",
        ),
        migrations.RemoveField(
            model_name="venta",
            name="id_producto",
        ),
        migrations.CreateModel(
            name="DetalleVenta",
            fields=[
                ("id_detalle", models.AutoField(primary_key=True, serialize=False)),
                ("cantidad", models.IntegerField()),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.producto"
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="home.venta",
                    ),
                ),
            ],
        ),
    ]
