# Generated by Django 5.0.6 on 2025-06-21 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_compra_fecha_entrega_alter_compra_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='id_proveedor',
        ),
        migrations.AddField(
            model_name='compra',
            name='producto_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.productoproveedore'),
        ),
        migrations.AddField(
            model_name='productoproveedore',
            name='precio_proveedor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio al que vende este proveedor este producto', max_digits=10, null=True),
        ),
    ]
