# Generated by Django 5.2.3 on 2025-06-21 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_compra_id_producto_remove_compra_id_proveedor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='producto_proveedor',
        ),
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('COMPLETADA', 'Completada'), ('REEMBOLSADA', 'Reembolsada'), ('PARCIALMENTE_REEMBOLSADA', 'Parcialmente Reembolsada'), ('ANULADA', 'Anulada')], default='COMPLETADA', max_length=30),
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha_modificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.proveedore'),
        ),
        migrations.AddField(
            model_name='compra',
            name='total_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('REEMBOLSADO', 'Reembolsado'), ('PARCIALMENTE_REEMBOLSADO', 'Parcialmente Reembolsado')], default='ACTIVO', max_length=30)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='home.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ReembolsoCompra',
            fields=[
                ('id_reembolso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('total_devuelto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reembolsos', to='home.compra')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReembolsoCompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.producto')),
                ('reembolso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='home.reembolsocompra')),
            ],
        ),
    ]
