# Generated by Django 5.2.1 on 2025-05-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=40, unique=True)),
                ('contraseña', models.CharField(max_length=30)),
            ],
        ),
    ]
