# Generated by Django 4.2.1

from django.db import migrations
import os

def crear_superusuario(apps, schema_editor):
    """
    Crea un superusuario utilizando variables de entorno.
    """
    Usuario = apps.get_model('usuario', 'Usuario')

    username = os.environ.get('DJANGO_SUPERUSER_USERNAME')
    email = os.environ.get('DJANGO_SUPERUSER_EMAIL')
    password = os.environ.get('DJANGO_SUPERUSER_PASSWORD')

    if username and email and password:
        if not Usuario.objects.filter(nombre_usuario=username).exists():
            # El manager ahora sabe cómo crear superusuarios
            Usuario.objects.create_superuser(
                nombre_usuario=username,
                correo=email,
                password=password
            )

class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(crear_superusuario),
    ] 