# Generated by Django 4.2.7 on 2025-06-23 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
    ]
