# Generated by Django 5.2.1 on 2025-06-23 04:02

from django.db import migrations
import os
from django.conf import settings

def crear_superusuario(apps, schema_editor):
    Usuario = apps.get_model('usuario', 'Usuario')
    
    username = os.environ.get('DJANGO_SUPERUSER_USERNAME', 'admin')
    email = os.environ.get('DJANGO_SUPERUSER_EMAIL', 'admin@example.com')
    password = os.environ.get('DJANGO_SUPERUSER_PASSWORD', 'admin1234')

    # Usamos create_superuser del manager personalizado
    if not Usuario.objects.filter(nombre_usuario=username).exists():
        Usuario.objects.create_superuser(
            nombre_usuario=username,
            correo=email,
            password=password
        )

class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(crear_superusuario),
    ]
