# Generated by Django 4.2.7 on 2025-06-22 21:56

from django.db import migrations
from django.contrib.auth.models import User


def crear_superusuario(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    if not User.objects.filter(username='admin').exists():
        User.objects.create_superuser(
            username='admin',
            email='admin@example.com',
            password='admin123'
        )


def reverse_crear_superusuario(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.filter(username='admin').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_correo'),
    ]

    operations = [
        migrations.RunPython(crear_superusuario, reverse_crear_superusuario),
    ]
