# Generated by Django 4.2.7 on 2025-06-23 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_crear_superusuario_admin'),
        ('usuario', '0004_crear_superusuario'),
    ]

    operations = [
    ]
