# Generated by Django 5.2.1 on 2025-06-14 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("producto", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="proveedor",
        ),
        migrations.DeleteModel(
            name="Categoria",
        ),
        migrations.DeleteModel(
            name="Producto",
        ),
        migrations.DeleteModel(
            name="Proveedor",
        ),
    ]
