# Generated by Django 5.2.1 on 2025-06-14 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0003_usuario_correo"),
        ("venta", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reembolso",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="usuario.usuario",
            ),
        ),
    ]
