# Generated by Django 5.2.1 on 2025-06-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venta", "0002_alter_reembolso_usuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionBoleta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(default="Ferretería El Ingeniero", max_length=100),
                ),
                (
                    "direccion",
                    models.CharField(
                        default="Av. Principal 123, Ciudad", max_length=200
                    ),
                ),
                (
                    "fono",
                    models.CharField(default="Fono: +56 9 1234 5678", max_length=50),
                ),
                ("rut", models.CharField(default="RUT: 12.345.678-9", max_length=20)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="boleta_logos/"),
                ),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
