# Generated by Django 5.2.1 on 2025-06-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venta", "0003_configuracionboleta"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionboleta",
            name="correo",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="configuracionboleta",
            name="mensaje_pie",
            field=models.CharField(
                blank=True, default="¡Gracias por su compra!", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="configuracionboleta",
            name="mostrar_codigo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="configuracionboleta",
            name="mostrar_descuento",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="configuracionboleta",
            name="mostrar_iva",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="configuracionboleta",
            name="sitio_web",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
