# Generated by Django 5.0.6 on 2025-06-14 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0006_remove_configuracionboleta_mostrar_descuento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracionBoleta',
        ),
        migrations.RemoveField(
            model_name='reembolsodetalle',
            name='reembolso',
        ),
        migrations.RemoveField(
            model_name='reembolsodetalle',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Reembolso',
        ),
        migrations.DeleteModel(
            name='ReembolsoDetalle',
        ),
    ]
